### ISSUE TITLE
gmsp in spectator

### ISSUE THREAD

**Issue by devramsean0** [theAspenGrove/SafeSpectate#5]
so theres the spectator reset location bug.

so i have a suggestion :)
when u run /gmsp in spectator it takes u into survival.
and when u run /gms in survival it takes u into spectator

**Comment by n-aspen** [comment]
Wouldn't it be better to just have 1 command at that point? Like, if both commands act exactly the same then why have two?

**Comment by devramsean0** [comment]
i keep doing /gmsp in spectator :)

**Comment by n-aspen** [comment]
I think having only one command would solve that too lol

**Comment by devramsean0** [comment]
ye

**Comment by n-aspen** [comment]
I'm not sure what command would work to be honest, but I'll make an announcement in discord to ask. It won't be hard to develop the system as just a toggle instead of two separate commands.

**Comment by n-aspen** [comment]
Looks like `/gmtoggle` works. Seeing as there would only be two gamemodes to switch through, I think it fits.

**Comment by devramsean0** [comment]
oki
closing the thread

**Comment by n-aspen** [comment]
> oki
> closing the thread

Uh, this should stay open until I implement it, lol

**Comment by devramsean0** [comment]
oh lol i thought u had implemented it lol

**Comment by n-aspen** [comment]
implemented in [1.2](https://github.com/theAspenGrove/SafeSpectate/tree/1.2)
